ARG NODE_IMAGE=node:18.15-alpine3.17

FROM $NODE_IMAGE AS base
RUN apk --no-cache add dumb-init
RUN mkdir -p /app && chown node:node /app
WORKDIR /app
USER node

FROM base AS development
ENV NODE_ENV=development
ENV PORT=3000
ENV HOST=0.0.0.0
ENV APP_KEY=fOqCggLg7Ch5Pe71jT5-TKz1SFdn0QjK
ENV DRIVE_DISK=local

COPY --chown=node:node ./package*.json ./
RUN npm install

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]